### ISSUE TITLE
NPE on item transfer

### ISSUE THREAD

**Issue by Macrophage001** [CyclopsMC/IntegratedTunnels#58] opened 2017-09-20 21:31 UTC
I'm not sure if this issue stems from Tiny Progressions or Integrated Tunnels but it seems to be caused by their interaction. I used 8 tier 8 cobblestone gens from Tiny Progressions with an item interface connected to each and an item exporter connected to a drawer controller. As soon as I connected the item exporter and placed a variable to only allow cobblestone to enter the drawer controller, the game crashed.

Here is the crash report:

[crash-2017-09-20_17.22.42-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/1319310/crash-2017-09-20_17.22.42-server.txt)

**Comment by rubensworks** [comment] 2017-09-21 06:45
This seems to be caused by an invalid target inventory.

Can you try hooking up your interface to a regular chest instead of a drawer controller instead, and see if that still crashes?

**Comment by Macrophage001** [comment] 2017-09-24 13:02
The same issue does not occur. Only when I try to place a item exporter onto a drawer controller Does it crash

**Comment by rubensworks** [comment] 2017-09-24 13:18
Sounds like an issue with Storage Drawers then, something with their sided item handler capability must be going wrong. Can you report it on their issue tracker and link back here?

**Comment by Macrophage001** [comment] 2017-09-26 11:56
Sorry it took so long. Here you go:

https://github.com/jaquadro/StorageDrawers/issues/575

**Comment by jaquadro** [comment] 2017-09-27 00:09
I need more information on the inventory usage.  It looks like SD blocks are being treated as IInventories, but they do not support that interface.  Only IItemHandler.

**Comment by rubensworks** [comment] 2017-09-27 06:38
@jaquadro IT only works with the `IItemHandler` capability, and never works with the old `IInventory`. I also never do a manual `InvWrapper` wrapping. So I assume another mod must be causing this.

@Macrophage001 Are you sure that your IT item interface is attached to a block of Storage Drawers? And not some kind of chest? Because the crashlog indicates that a corrupted `InvWrapper` is being used, which is only possible on a vanilla chest, and maybe some other mod inventories.

**Comment by Macrophage001** [comment] 2017-09-27 10:49
No, the item interfaces are connected to the cobblestone generators and the item exporter is connected to the drawer controller. I'll take a picture of my setup when I get back from work. It's basically 8 Cobblestone Generators with item interfaces on each, then a drawer controller directly above them with an item exporter connected to it. Everything is connected together but the crash occurs once I place the blank variable card into the item exporter.

**Comment by rubensworks** [comment] 2017-09-27 22:10
Note to self: find out if I am using `InvWrapper` myself anywhere somehow.

**Comment by Macrophage001** [comment] 2017-09-27 22:52
![error_construct](https://user-images.githubusercontent.com/331135/30941741-f638e95a-a3b4-11e7-8265-809db414f900.png)

Here's the setup. As soon as I put in a variable card in that item exporter, it crashes.

**Comment by rubensworks** [comment] 2017-09-27 23:16
@Macrophage001 Thanks!

Until I have time to look into this, could you try this setup with item importers instead of the interfaces, and an interface instead of the exporter?

**Comment by rubensworks** [comment] 2017-09-27 23:41
Ah, but wait...

The cobble generators seem push items to the interface themselves. Because of how IT interfaces work, these items will be pushed to the other blocks that the interfaces are targetting, i.e., the other cobble generators. So the cobble generator blocks must be exposing an invalid item handler capability. More specifically, they expose an item handler which can contain `null` ItemStacks, instead of `ItemStack.EMPTY`.

@Macrophage001 Could you report this to the mod author of those cobble generators?

The setup described in my previous comment should work in any case.

**Comment by Macrophage001** [comment] 2017-09-28 01:27
A different error occurs when I try the item importers setup:

[crash-2017-09-27_21.25.21-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/1339136/crash-2017-09-27_21.25.21-server.txt)

And will do.

**Comment by Kashdeya** [comment] 2017-09-28 05:37
This issue has been fixed in our Tiny progressions workspace and will be in our next update.

**Comment by rubensworks** [comment] 2017-09-28 06:46
Ok, great! Closing this issue then :-)

**Closed as completed by rubensworks** 2017-09-28 06:46 UTC
Labels: bug
