### ISSUE TITLE
Crash when attaching to tinkers construct casting table or basin

### ISSUE THREAD

**Issue by dhagerich** [CyclopsMC/IntegratedTunnels#11] opened 2017-01-10 12:51 UTC
Whenever i try to add a blank variable card to an importer/exporter that has a tinkers construct casting table/basin attached to the network, the game crashes. I've attached the crash report for you.

[crash when adding variable to importer attached to tcon casting table.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/696120/crash.when.adding.variable.to.importer.attached.to.tcon.casting.table.txt)

**Comment by rubensworks** [comment] 2017-01-10 12:54
Duplicate of #10, which has been fixed on TCon's end.

**Closed as completed by rubensworks** 2017-01-10 12:54 UTC
Labels: duplicate

**Comment by dhagerich** [comment] 2017-01-10 14:11
sorry a bit tired here, I forget to check closed issues before i posted
