### ISSUE TITLE
Support for gasses(mekanism)

### ISSUE THREAD

**Issue by Emotional-Support** [CyclopsMC/IntegratedTunnels#269] opened 2023-06-04 05:04 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

It would be nice if you could look into adding support for mekanism gasses. I know there have been two other requests about this, but both are 5 and 6 years old at this point, so i thought id try asking again. thanks

**Comment by rubensworks** [comment] 2023-06-04 05:04
Thanks for the suggestion!

**Comment by rubensworks** [comment] 2023-06-04 05:07
Duplicate of #128

**Closed as not planned by rubensworks** 2023-06-04 05:07 UTC
Labels: feature-long-term
