### ISSUE TITLE
Unrecoverable crash on Server after placing world fluid exporter

### ISSUE THREAD

**Issue by yujukitten** [CyclopsMC/IntegratedTunnels#93] opened 2017-12-12 01:00 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:
I was attempting to automate terracotta creation in wooden barrels and upon testing different connectors to the barrel. I had a severe crash and could only get back into the server after rolling back.
It was a world Fluid exporter that I had placed directly before the crash.

#### Expected behaviour:
Expected it to export water into the barrel. 

#### Actual behaviour:

Errored and crashed server. recieve pipe errors upon each attempt to restart and another shutdown.

#### Steps to reproduce the problem:

1. ... Sink from cooking for blockheads ( set to infinite water) , fluid interface on side , logic cable, then the world fluid importer. ( which I placed after I had already placed the ex nihilo creatio wooden barrel down. 

____
#### Versions:

- This mod: 1.12.2.1.3.5
-integrated dynamics 1.12.2.0.9.6  = in case It is this one that is actually the issue
- CyclopsCore: 1.12.2.0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2560

#### Log file:
first crash
[crash-2017-12-11_18.13.52-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/1549906/crash-2017-12-11_18.13.52-server.txt)

one of the subsequent crashes
[crash-2017-12-11_18.15.55-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/1549907/crash-2017-12-11_18.15.55-server.txt)

**Comment by josephcsible** [comment] 2017-12-12 01:35
Duplicate of #84, #86, and #87.

**Closed as completed by josephcsible** 2017-12-12 01:35 UTC
Labels: duplicate
