### ISSUE TITLE
Item Importer acting slow

### ISSUE THREAD

**Issue by LemmaEOF** [CyclopsMC/IntegratedTunnels#59] opened 2017-09-27 07:06 UTC
I'm trying to use Integrated Tunnels to automate tinker's construct smeltery casting, but for some reason the item importer is acting really, really slow. Its frequency is set to 1 and it's definitely got a value of true for import all items, but it's just not doing it as often as it should. It does work eventually, but can sometimes take up to thirty seconds. Any idea what's up?

Video of issue: https://streamable.com/q4f92

Summary of system: Redstone writer pointed at seared faucet checks if a redstone signal from redstone reader is on and a variable (that checks if there's fluid in the smeltery and the casting table is not full) is true. If all three parts are true, the writer activates the faucet, casting an item. Then, the importer checks to see if both the redstone reader is on and the casting table inventory is true. If so, then the importer imports all items.
The system worked perfectly but then just stopped working for some reason. Any idea if I'm doing something wrong?

**Comment by LemmaEOF** [comment] 2017-09-27 07:08
It works every so often, but the time between each extract after the metal solidifies just gets even longer until it's totally unreasonable.

**Comment by rubensworks** [comment] 2017-09-27 07:10
I already know what is going wrong. The transfer optimization system probably still thinks that the inventory is empty, while it isn't anymore. Will look into it.

**Comment by LemmaEOF** [comment] 2017-09-27 07:12
Thank you for the quick response! Yeah, WAILA shows the casting table as "empty" too even though there's clearly an ingot there, though it might just be referring to the fluid tank.

**Comment by rubensworks** [comment] 2017-09-27 07:18
Hmm, does WAILA show something in the tooltip of the casting table if there has been an ingot in there for a while? There might be something else wrong in that case.

But I'll look into it.
On holidays now, so it might be a while before I can fix it.

**Comment by vitalexbel** [comment] 2017-09-27 12:36
I have the same issue with regular chests.
The system imports items normally from some chests.
But from the other chests I have to wait ~40 seconds.
I use minecraft chests, item importers and empty cards in Import All Items slot in importer.

**Comment by rubensworks** [comment] 2017-09-27 22:08
@vitalexbel Thanks for the information, good to know that the issue doesn't only occur with the casting table.

**Comment by DaComputerNerd717** [comment] 2017-10-09 00:28
I am also experiencing this issue, for a completely different system.

My system at this point is a little bit simpler. The network is transferring power and canola seeds from a chest into Actually Additions display stands, which are then used by empowerers to empower some crystallized canola seeds. At first, I thought it was just completely stopping, but, after watching it, this seems to be the issue. I am also using an empty variable card to transfer all items. 

This is in All The Mods 3 version 4.0. 

Another thing I noticed is that, sometimes, this system has the beams from the empowerer active when the items aren't in the display stands, as though the empowerer expects the items to be there, but they aren't.

Edit 2: So I looked at the server console, and I noticed errors for a system which, among other things, powered this system. No relations in item connections. This was the error:

[20:19:28] [Server thread/ERROR] [Integrated Dynamics]: The position at BlockPos
{x=-796, y=61, z=91} was incorrectly marked as reachable as path element by org.
cyclops.integrateddynamics.core.tileentity.TileCableConnectable$1@38d84236 at Bl
ockPos{x=-795, y=61, z=91} side west.

By replacing the cable at -795 61 91, suddenly the not connected empowering system started working. Not sure why.

**Comment by LemmaEOF** [comment] 2017-10-09 01:03
The new version of Integrated Dynamics fixed it for me. @RedstoneMaster256, I recommend maybe manually updating Integrated Dynamics?

**Comment by DaComputerNerd717** [comment] 2017-10-10 02:10
ATM3 has now updated again, updating a lot of mods, including this one.

**Comment by DSLM** [comment] 2017-10-12 17:02
I have the same problem in 1.10.2(IT 1.2.5), I want to import everything from auto hammer, but it is slowly, and even won't work sometimes.
When it stop, I chage the Item Transfer Rate to 1, 63 or 65, it will work so fast.
When I change it to -1, it work similarly to a exporter, but this is what it did: 
![image](https://user-images.githubusercontent.com/12635058/31524640-0f249b64-af89-11e7-8dc5-d8b689f0ddc4.png)
see https://github.com/CyclopsMC/IntegratedTunnels/issues/60 for more details about this bug.

**Comment by rubensworks** [comment] 2017-10-24 11:04
I just pushed a new change with regards to the item inventory caching system (which was probably causing the problem).

Would someone here be able to try the latest dev build (link in README, still building at the time of writing), and see if this resolves the issue for you?

**Comment by rubensworks** [comment] 2017-10-30 10:55
Assuming resolved.

**Closed as completed by rubensworks** 2017-10-30 10:55 UTC
Labels: bug, mc-1.12

**Comment by fiws** [comment] 2017-12-24 16:35
I think I have the same problem with the Block breaker from Actually Additions. The one probe shows a full inventory. Seems it only transfers every ~ 5 seconds.

**Comment by rubensworks** [comment] 2017-12-25 09:36
@fiws You _think_ so? Or can you consistently reproduce it in a clean environment? Also, are you using the latest mod versions?

**Comment by fiws** [comment] 2017-12-25 13:58
@rubensworks I was experiencing this. I manually placed blocks into the breaker and saw nothing happening for a few seconds. 

But of course… as soon as i try to reproduce this everything works again (even with my original setup).

**Comment by fiws** [comment] 2017-12-25 15:38
Aaand, it happened again. Took some time to occur again. Could it be an issue with my (extra utilities) chunk loader?

Video: https://i.imgur.com/4l0Enob.mp4

Edit: Replacing one cable fixes the problem again

**Comment by rubensworks** [comment] 2017-12-25 18:57
@fiws What happens when you use another aspect to import the items? Does it also take this long?

Would you be able to figure out what triggers it in your case? And what makes it go away again?
