### ISSUE TITLE
Why don't importers respect channels they are set to?

### ISSUE THREAD

**Issue by Pultex** [CyclopsMC/IntegratedTunnels#180] opened 2020-01-10 06:25 UTC
#### Issue type:

- :question: Question
why do energy export tunnels support channels but imports do not?

____

#### Question:

If you set a energy interface to channel 45 then set the energy export to 45 it will export energy from the external provider to the external receiver only on that channel.
If you set a energy importer to the same channel 45 it will error with a "simulation Failure" text error after a few ticks of it being valid, if you change the energy interface to 0 it will work again even though the importer is on still on channel 45.

All item importers just ignore all channels and import to anything on the network that has a interface attached to it that can accept the item in transit.

Did not see anyone having this issue so figured it was a design decision not a bug.

**Comment by rubensworks** [comment] 2020-01-10 07:05
It sounds like this may be a bug, but may also be caused by some other mod.

Could you close this issue and create a new bug report issue where you include all of the required information?

**Closed as completed** 2020-01-24 07:51 UTC
Labels: question, more-information-needed
