### ISSUE TITLE
Server crash with Biome Crystals

### ISSUE THREAD

**Issue by wrincewind** [CyclopsMC/IntegratedTunnels#106] opened 2018-01-10 19:39 UTC
#### Issue type: Crash

- :bug: Bug
____
#### Short description:
When I put an item card set to 'Biome Crystal: Storage Cell' from the Random Things mod into the 'Export Item' slot of an item exporter, the server crashes, booting me out with an error of 'server closed' and causing the server to reboot. The same thing happens when the Biome Crystal is the first/only item in a list card,  and happens irrespective of the exporter's settings for ignoring/respecting damage/nbt/etcetera. 

I also tried it with a different Biome Crystal (Forest, specifically) in a Dynamic Light Panel and got the same thing. So it seems to be more generic than just that specific biome.

#### Expected behaviour:

The Item Exporter should pull all biome crystals (or all biome crystal:Storage Cells) from the rest of the system (A handful of small crates from Actually Additions) into the crate it's attached to.

#### Actual behaviour:
When placed into the GUI, the client freezes for a few moments before booting me from the server, with the error message 'server closed'. Upon reboot, any attempt to access the GUI of the offending Item Exporter will result in another crash, requiring me to break the exporter to get my card back.

#### Steps to reproduce the problem:

1. Place down a chest (crate, etc, it seems to work on both so probably anything... but there's only so many tests I can do before the admin yells at me to stop crashing his server, this is like the sixth time)

2. Place an item exporter and at least 1 piece of cable onto the chest

3. in your portable logic controller (... or whatever the doohickey's called), select either 'item' or 'list' > 'item', then take a Biome Crystal from Random Things (I used Biome Crystal: Storage Cell) and place it in the slot, along with a blank variable card to get your item or list variable.

4. place your item or list variable in the appropriate slot of the Item Exporter. 

5. The server should crash.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 
- CyclopsCore: 1.12.2-0.11.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2582

#### Log file:

https://pastebin.com/4ijPuppn

 https://imgur.com/a/JW5jJ < pictures of the two cards I used, with advanced NBT Data shown.

**Comment by rubensworks** [comment] 2018-01-10 19:41
Could you share the crashlog? I can't find it in the log you provided.

**Comment by wrincewind** [comment] 2018-01-10 20:00
Let me ask the admin of the server - my client didn't crash, it just booted me off the server. I'm playing SMP, sorry for not mentioning that sooner. 

I can confirm that the crash does *not* occur in single player when using a *blank, cheated in* biome crystal. Trying to get a non-cheated one is proving a little challenging, so a single-player crash log might take a little longer...

**Comment by wrincewind** [comment] 2018-01-10 20:09
Okay, tried doing it in a single player world on the same instance, and it worked fine - no crash, no GUI error, nothing.  

this should be the latest crashlog. 
http://www.sillydragon.ca/Minecraft/Live%20Server/crash-reports/crash-2018-01-10_12.34.00-server.txt

**Comment by rubensworks** [comment] 2018-01-10 20:28
Hmm, it seems to be caused by Random Things that calls `Biome#getBiomeName` (which is client-side only) from within `Item#getItemStackDisplayName` (server-side).

Typically, this isn't a problem, but ID calls this server-side.
Ideally, the stack itself should be sent to the client, but due the way it works now, this would require a lot of hacking.

Note to self: add a (temp?) try-catch around this because similar issues may occur in the future, and fall back to a safer way to get the item name.

**Comment by wrincewind** [comment] 2018-01-10 20:31
Fair enough! So, sounds like it's an issue with Random Things. You wanna go tell 'em, or shall I?

Also, got any suggestions for safe ways to filter these? I think I can do something with having the name equal a string, but I'm not sure about partial matches.

**Comment by rubensworks** [comment] 2018-01-10 20:34
No, no need to tell them. It's something that should be handled better in ID. RT does nothing wrong.

**Comment by rubensworks** [comment] 2018-01-13 12:37
Fixed in https://github.com/CyclopsMC/IntegratedDynamics/commit/7ba9c85490bef42d0ba7ac06334d3930caad2980

**Closed as completed by rubensworks** 2018-01-13 12:37 UTC
Labels: bug, mc-1.12
