### ISSUE TITLE
[1.12.2][1.3.5] World Fluid Exporter Crashes Game on Export All Fluids

### ISSUE THREAD

**Issue by Rosethorns** [CyclopsMC/IntegratedTunnels#86] opened 2017-12-03 09:39 UTC
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
____
#### Short description:
Game Crashes when placing a blank variable card into the "export all fluids" slot of a World Fluid Exporter

#### Expected behaviour:
For the World Fluid Exporter to place the lowest priority fluid in the network

#### Actual behaviour:
Game Crashes when placing a blank variable card into the "export all fluids" slot of a World Fluid Exporter.
The World Fluid Exporter doesn't even need to be connected to a valid network for the crash to occur and the crash occurs even if it is a valid network (Tank>fluid interface>cable>world fluid exporter)

#### Steps to reproduce the problem:

1. place variable card into the "export all fluids" slot of the World Fluid Exporter
2. crash
____
#### Versions:

- This mod: 1.12.2-1.3.5
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2556

#### Log file:

https://pastebin.com/7W4HrF6V

**Comment by josephcsible** [comment] 2017-12-03 14:52
Duplicate of #84, already fixed in dev and will be fixed in the next version

**Closed as completed by josephcsible** 2017-12-03 14:52 UTC
Labels: duplicate
