### ISSUE TITLE
Copy settings from one interface to another

### ISSUE THREAD

**Issue by LKakha** [CyclopsMC/IntegratedTunnels#300] opened 2024-08-07 13:15 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

We are able to make the copy of variable card by placing on crafting grid source and blank cards together, so would be nice if we could copy options of interfaces same way -  ticks, priority and channel, (and offset if possible).

**Comment by rubensworks** [comment] 2024-08-07 13:16
Thanks for the suggestion!

**Comment by rubensworks** [comment] 2024-08-07 13:28
Duplicate of https://github.com/CyclopsMC/IntegratedDynamics/issues/859

**Closed as not planned by rubensworks** 2024-08-07 13:28 UTC
Labels: feature-long-term
