### ISSUE TITLE
Fluid Import-Export Crash

### ISSUE THREAD

**Issue by Thornstromb** [CyclopsMC/IntegratedTunnels#87] opened 2017-12-04 04:39 UTC
#### Issue type:
- :bug: Bug

____
#### Short description: 
Attempting to make a superbasic fluid tank-to-world logic pipe (fluid import, fluid world export) causes an immediate crash, and autocrashes the world on reloading.

#### Expected behaviour:
Fluid will be exported onto target block, no crash

#### Actual behaviour:
CRASH.

#### Steps to reproduce the problem:

1. Start game with ID/IT installed
2. Place a tank of water (from any mod) and a logic pipe with a fluid importer and a Fluid World Exporter.
3. Insert basic Variable card into importer on "import All"
4. Insert basic Variable card into exporter on "export all", Watch game die.
5. attempt to log in again, watch game die again.
____
#### Versions:

- This mod: 1.3.5
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2556

Note: running FTB Horizons 3 version 1.3.0 , crash log does not indicate any conflict triggers from other mods however.

#### Log file:

https://pastebin.com/Jp2V0UV1
(from creative test world bug check attempt)

**Comment by josephcsible** [comment] 2017-12-04 12:16
Duplicate of #84 (and #86)

**Closed as completed by josephcsible** 2017-12-04 12:16 UTC
Labels: duplicate
