### ISSUE TITLE
Player simulation crash

### ISSUE THREAD

**Issue by darkshadow543** [CyclopsMC/IntegratedTunnels#70] opened 2017-11-04 14:10 UTC
MC: 1.12.2
IT: 1.3.4
ID: 0.9.4
CC: 0.10.22
Forge: 14.23.0.2528
Crashlog: https://pastebin.com/8r2niKLi
I think it might have to do with loading.

**Comment by rubensworks** [comment] 2017-11-04 23:06
Fake player seems to be null for some reason. This seems to be related to incorrect initialization indeed.

**Comment by homemmakako** [comment] 2017-11-06 22:29
I just had the same problem. It might be useless, but here is a second [crash log](https://pastebin.com/ken7bJDu) 😝

**Comment by rubensworks** [comment] 2017-11-08 10:24
@homemmakako Good thing you sent me that crashlog, because that was actually being caused by a completely different problem :-) Will be fixed in the next update.

**Closed as completed** 2017-11-08 12:27 UTC
Labels: bug, mc-1.12
