### ISSUE TITLE
Issue with Quantum Storage mod

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedTunnels#206] opened 2021-01-07 10:35 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Item interface can't interactive with QuantumStorage's QuantumController, I think this isn't QuantumStorage's problem, because other mods like RefinedStorage has no problem with it.
https://github.com/gigabit101/QuantumStorage/blob/1.16.3/src/main/java/net/gigabit101/quantumstorage/tiles/TileController.java
![javaw_9Czn469MeY](https://user-images.githubusercontent.com/50770712/103882635-14344680-5117-11eb-9ab3-6e4017c0af6d.png)
![javaw_LYcm0RUDfd](https://user-images.githubusercontent.com/50770712/103882641-15657380-5117-11eb-97c3-e1a5d2dd43e8.png)

#### Versions:

- This mod: 1.6.14
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by rubensworks** [comment] 2021-01-07 10:36
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-01-07 10:39
What does your setup look like? Can you share a screenshot?
How many slots does the terminal show (the line that just dropped out of your screenshot above)?
Do you see anything in the logs?
Do hoppers work with this quantum storage?

**Comment by shBLOCK** [comment] 2021-01-07 10:43
Oh, it just doesn't show on the terminal, I can use item importer to import items into the QuantumController.

**Comment by shBLOCK** [comment] 2021-01-07 10:46
The terminal shows that there are 320 slots with 5 StorageUnit, 5*64=320, so it's kind of right.

**Comment by rubensworks** [comment] 2021-01-07 11:03
And can you use the item exporter to export from the quantum storage?
If that works, then the items _should_ be present in your network.

How many slots do you see are filled in your terminal? 0?

What does your setup look like? Can you share a screenshot?

**Comment by shBLOCK** [comment] 2021-01-07 11:55
![javaw_r7dRWrRiZH](https://user-images.githubusercontent.com/50770712/103889919-2ebfed00-5122-11eb-8a96-b9ea1201c2a0.png)
![javaw_GA92Gf34ql](https://user-images.githubusercontent.com/50770712/103889924-3089b080-5122-11eb-8529-1c6a21ede8b9.png)
And the item exporter can export from the quantum storage.
![javaw_BvYZfyZLpb](https://user-images.githubusercontent.com/50770712/103890048-6038b880-5122-11eb-80c8-27e768a15790.png)
Refined Storage does work.

**Comment by rubensworks** [comment] 2021-01-07 12:00
That's interesting. Thanks for the additional details.

**Comment by shBLOCK** [comment] 2021-01-07 12:01
Yes, it's weird.

**Comment by rubensworks** [comment] 2021-01-09 15:19
Can't reproduce this myself with QS 5.3.0.

If anyone else can reproduce this problem, please share a reproducible setup here (without any other mods installed).

**Comment by shBLOCK** [comment] 2021-01-18 11:41
hmm,I already removed all other mods except JEI and TOP, but it doesn't work, I finded that I can click items into the controller, it just doesn't show up in the terminal.

https://user-images.githubusercontent.com/50770712/104910651-9698f200-59c4-11eb-8fc8-86294b205572.mp4

**Comment by rubensworks** [comment] 2021-01-18 11:42
I'll retry with your exact setup, as mine was slightly different during testing.

**Comment by rubensworks** [comment] 2021-01-18 19:22
It looks like quantum storage is only exposing a single slot containing an empty stack when invoking `IItemHandler.getStackInSlot` when connecting via the controller block, which is why Integrated Terminals is not detected any items inside of it.

@gigabit101 Any idea what might be going wrong?

**Comment by gigabit101** [comment] 2021-01-20 20:44
Yes, I'm a moron lol, Will fix when I have some free time

**Comment by rubensworks** [comment] 2021-01-21 07:41
Thanks for checking, will close this issue here in the meantime.

**Closed as completed by rubensworks** 2021-01-21 07:41 UTC
Labels: bug, other mod, mc-1.16
